name: RoyalCutsforMen
favicon: null
layout_spectrum: 0.0434013893827796
typography_spectrum: 0.02923833974637091
title: 'Royal Cuts for Men Cypress, Texas'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.238616400398314
  lightness: 0.976739595644176
  saturation: 0.8601522634271532
  rhythmicContrast: 0.5728984328452498
purpose: []
